### ISSUE TITLE
[JOSS REVIEW] Documentation

### ISSUE THREAD

**Issue by zen-juen** [mad-lab-fau/BioPsyKit#11]
Hi there, when ticking off the documentation checks on https://github.com/openjournals/joss-reviews/issues/3702 I realize that there aren’t guidelines yet for potential contributors, collaborators, and those seeking support for software use. You may want to refer to https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors for doing so, as well as add some templates for writing issues and creating pull requests! 

Overall, I think the README is clear with short and succinct examples of use and are easily referred to when going through each section on different types of analysis in the paper (e.g., sleep analysis, biomarker analysis…). However, there is no documentation of how statistical analyses and machine learning pipelines (using `stats` and `classification`) can be readily implemented. As it's not intuitive yet on how this can be done, I think a short example script could be nice - perhaps the one used to generate the Figure 5 boxplot in the paper?

Let me know what you think!

**Comment by richrobe** [comment]
Thanks for your comments! We added guidelines for contributing to the repository starting with 0db7ab5763ed72ed608e69c9c234c45a3cfa94e9 (and the commits followed after that). Additionally, we added bug report, feature requests, and pull request templates in 4368da3474f06098fbe4d76b286c4aefab6c8810 and a88fbfd6e8c547dc551e3d3080d4746cd2080d29.

**Comment by richrobe** [comment]
Regarding your other idea: I think that's a good idea! The `stats` and `classification` modules are already briefly explained in the example Jupyter Notebooks `StatsPipeline_Plotting_Example` and `SklearnPipelinePermuter_Example`. The code for generating the Figuer 5 boxplot in the paper can be found in the `Questionnaire_Example` notebook (at the very end). We can describe the features in more detail in the respective example notebooks. Additionally, I can also add some brief examples code directly to the README?

**Comment by richrobe** [comment]
We updated the README to include the minimal example codes in b00bc44e6834021a1c97e987daf58f67c341d776!
