### ISSUE TITLE
MIST code

### ISSUE THREAD

**Issue by rickinelson** [mad-lab-fau/BioPsyKit#24]
hi, tanks for the BioPsyKit, I have a question, this package have the MIST task or is only to precess the data of the MIST, I would like to implement in a experimental setting but I can't run the MIST using this package. do you have the MIST in python code?

**Comment by richrobe** [comment]
Hi @rickinelson, sorry for the late response!

Yes, the MIST module in biopsykit is only to process data collected during the MIST.

However, we have another project that reimplemented the MIST task as web-application: https://www.zimt.fau.eu/stress/. Let me know if you have more questions!
