### ISSUE TITLE
ActivityCount converts tiemstamps to Europe/Berlin

### ISSUE THREAD

**Issue by rouzbeh** [mad-lab-fau/BioPsyKit#30]
This line:
https://github.com/mad-lab-fau/BioPsyKit/blob/cc743d7b042151cddd90c50ac5599646f6d8e487/src/biopsykit/signals/imu/activity_counts.py#L177
Converts all timestamps to Europe/Berlin. I believe this should be avoided, or at least be configurable.

**Comment by richrobe** [comment]
Hi @rouzbeh,

thank you for the hint! Indeed, this should be configurable. Happy to patch this into BioPsyKit if you create a pull request for it 😊
