### ISSUE TITLE
What is the expected convention for sleep?

### ISSUE THREAD

**Issue by rouzbeh** [mad-lab-fau/BioPsyKit#35]
This line seems to indicate that sleep is marked as 0.
https://github.com/mad-lab-fau/BioPsyKit/blob/376e3a04f80e68daa6d36f8ecd1e1b527a8d7193/src/biopsykit/sleep/sleep_endpoints/sleep_endpoints.py#L44

But this line seems to contradict it:
https://github.com/mad-lab-fau/BioPsyKit/blob/376e3a04f80e68daa6d36f8ecd1e1b527a8d7193/src/biopsykit/sleep/sleep_endpoints/sleep_endpoints.py#L61

**Comment by richrobe** [comment]
Hi @rouzbeh, thanks for pointing this out! The expected convention is *1* for sleep and *0* for wake. Hence, it's a typo in the documentation. I will update it accordingly!

**Comment by richrobe** [comment]
fixed in 4684da2
